title: Makeup by Allie
description: 
theme: jekyll-theme-beautiful

logo: /images/baddieallie.png

show_downloads: false

social_links:
  instagram: yourinstagram
  github: yourgithub

collections:
  nails:
    output: true
  paintings:
    output: true
  clothing:
    output: true
  sculpture:
    output: true
