title: Makeup by Allie
description: Soft Glam • Editorial • Special Occasions • Pacific Northwest
theme: jekyll-theme-cayman

show_downloads: false

github_username:
twitter_username:

plugins:
  - jekyll-seo-tag
